[package]
name = "surreal_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.38", features = ["full"] }
quote = "1.0.33"
serde = { version = "1.0.118", features = ["derive"]}
serde_json = "1.0.107"
surrealdb = "1.0.0"
proc-macro2 = "1.0.67"
darling = "0.20.3"
surreal_devl = { path= "../surreal-devl" }
