[package]
name = "surreal_derive_plus"
version = "1.0.7"
edition = "2021"
description = "Query builder for surrealdb"
readme = "README.md"
repository = "https://github.com/dev-logs/surreal-derive"
license = "MIT OR Apache-2.0"
keywords = ["surreal", "surrealdb", "db", "query-builder"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.38", features = ["full"] }
quote = "1.0.33"
surrealdb = "1.0.0"
proc-macro2 = "1.0.67"
surreal_devl = "1.0.1"

[dev-dependencies]
serde = { version = "1.0.118", features = ["derive"]}
serde_json = "1.0.107"