[package]
name = "devl-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.37"
quote = "1.0.33"
serde = { version = "1.0.118", features = ["derive"]}
serde_json = "1.0.107"
surrealdb = "1.0.0"
proc-macro2 = "1.0.67"
